### ISSUE TITLE
Muck Arrows and Muck Food has issues with ObamiumStuff Mod Where you cant move with either muck food or just muck arrows installed with Obamium Mod

### ISSUE THREAD

**Issue by Valk117** [Michmcb/MuckMods#1]
Hey sorry this post is to late just wanted to say that your mods dont work with the ObamiumStuff Mod ive tried everything to get it to work but sadly i have no idea what the issue is. Once you load in with ObamiunStuff and you have the Mushroom mod or the arrow mod enabled as well you cant move at all your stuck in place id really love to play with all these mods but if your done with muck i completely  understand anyways thank you so much for these beautiful creations your a legend man!!

**Comment by Michmcb** [comment]
Right, thanks for letting me know. I've just tested, and I've been able to reproduce the bug, so I should be able to get it fixed. I'll slap the Stack Trace here so I don't forget it.


[Error  : Unity Log] ArgumentException: An item with the same key has already been added. Key: 152
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <2b3a3162be434770b7a4fac8b896e90c>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <2b3a3162be434770b7a4fac8b896e90c>:0)
MuckArrows.CreateRecipesPatch.ItemManager_InitAllItems () (at <939e2dca06884a9da1321b40b86f680d>:0)
ItemManager.InitAllItems () (at <8db17789d6d548de86abe696a5ff6b2b>:0)
ItemManager.Awake () (at <8db17789d6d548de86abe696a5ff6b2b>:0)

**Comment by Michmcb** [comment]
All fixed! Sorry for closing/reopening/closing again, fumbling a bit. Anyway; MuckArrows, MuckCharcoal, MuckFoods, and MuckSaveGame all had bugfixes applied. If you were using any of those mods, you ought to download the latest version. I've uploaded them to thunderstore.io.
