### ISSUE TITLE
Muck Save game is incompatible with these mods

### ISSUE THREAD

**Issue by DeadbushCarrot** [Michmcb/MuckMods#3]
If you can't add support for all these mods its fine not all will be
Heres the list 

Muck upgrade buildings - Saving / Loading just doesn't work

Item choice - Can't hit anything only when loading into a save

Bigger map - Doesn't save the map settings | like how big the map was, or how many caves there

**Comment by Michmcb** [comment]
Hey, wanted to let you know that I've read this issue so I'm aware of this. I'll get onto this when I have some spare time.

**Comment by DeadbushCarrot** [comment]
Okay!

**Comment by Michmcb** [comment]
Okay, question for Item Choice - did you install this mod on an existing world that did not have the mod installed, and then attempted to keep playing on your world with it?

**Comment by DeadbushCarrot** [comment]
Let me retest it

**Comment by DeadbushCarrot** [comment]
So I what I did was I installed the mod on a world where it wasn't and the glitch happened I retested it but had the mod installed on a new world and it was fine so its only when loading into a old world when it wasn't installed

**Comment by Michmcb** [comment]
I've raised issues #4, #5, and #6, one for each individual incompatibility, to better track them, and close this one out.
